/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle_de_gasto;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class Formulario_Inserir_Gasto extends javax.swing.JFrame {
    private Gasto gasto;
    private boolean update = false;
    /**
     * Creates new form Formulario_Inserir_Gasto
     */
    public Formulario_Inserir_Gasto() {
        initComponents();
        KeyAdapter numOnly = new KeyAdapter(){
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c!=',')) {
                    e.consume();
                }
            }
        };
        jTF_Valor.addKeyListener(numOnly);
        jTF_Abatimento.addKeyListener(numOnly);
        jTF_Juros.addKeyListener(numOnly);
        LocalDate date = LocalDate.now();
        String[] dateArray = date.toString().split("-");
        jCB_Dia.setSelectedItem(dateArray[2]);
        jCB_Mes.setSelectedIndex(Integer.parseInt(dateArray[1])-1);
        jCB_Ano.setSelectedItem(dateArray[0]); 
    }
    
    public Formulario_Inserir_Gasto(Gasto gasto) {
        initComponents();
        KeyAdapter numOnly = new KeyAdapter(){
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c!=',')) {
                    e.consume();
                }
            }
        };
        jTF_Valor.addKeyListener(numOnly);
        jTF_Abatimento.addKeyListener(numOnly);
        jTF_Juros.addKeyListener(numOnly);
        
        jTF_Descricao.setText(gasto.getDescricao());
        jTF_Valor.setText(String.valueOf(gasto.getValor()).replace(".", ","));
        jCB_Dia.setSelectedItem(String.valueOf(gasto.getDia()));
        String[] mes_ano = gasto.getMes().split("/");
        String mes = mes_ano[0];
        String ano = mes_ano[1];
        jCB_Mes.setSelectedItem(mes);
        jCB_Ano.setSelectedItem(ano);
        if(gasto.isAbatimento()){
            jCB_Abatimento.setSelected(true);
            jTF_Abatimento.setText(String.valueOf(gasto.getAbatimento_val()).replace(".", ","));
        }
        if(gasto.isJuros()){
            jCB_Juros.setSelected(true);
            jTF_Juros.setText(String.valueOf(gasto.getJuros_val()).replace(".", ","));
        }
        setUpdate(true);
        setGasto(gasto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jB_Cancelar = new javax.swing.JButton();
        jB_Continuar = new javax.swing.JButton();
        jCB_Mes = new javax.swing.JComboBox<>();
        jCB_Ano = new javax.swing.JComboBox<>();
        jCB_Dia = new javax.swing.JComboBox<>();
        jCB_Abatimento = new javax.swing.JCheckBox();
        jCB_Juros = new javax.swing.JCheckBox();
        jTF_Juros = new javax.swing.JTextField();
        jTF_Abatimento = new javax.swing.JTextField();
        jTF_Valor = new javax.swing.JTextField();
        jTF_Descricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Gasto");

        jLabel1.setText("Descrição do gasto");

        jLabel2.setText("Valor");

        jLabel3.setText("Data");

        jLabel4.setText("Adicionar Abatimento?");

        jLabel5.setText("Adicionar juros?");

        jB_Cancelar.setText("Cancelar");
        jB_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CancelarMouseClicked(evt);
            }
        });

        jB_Continuar.setText("Continuar");
        jB_Continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_ContinuarMouseClicked(evt);
            }
        });

        jCB_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        jCB_Ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jCB_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCB_Abatimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_AbatimentoActionPerformed(evt);
            }
        });

        jCB_Juros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_JurosActionPerformed(evt);
            }
        });

        jTF_Juros.setEditable(false);
        jTF_Juros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_JurosKeyTyped(evt);
            }
        });

        jTF_Abatimento.setEditable(false);
        jTF_Abatimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_AbatimentoKeyTyped(evt);
            }
        });

        jTF_Valor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTF_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ValorActionPerformed(evt);
            }
        });
        jTF_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_ValorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(jCB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCB_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(55, 55, 55)
                                        .addComponent(jCB_Juros))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jB_Continuar)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addComponent(jCB_Abatimento)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_Cancelar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTF_Abatimento, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                        .addComponent(jTF_Juros)))))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Abatimento)
                    .addComponent(jLabel4)
                    .addComponent(jTF_Abatimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jCB_Juros)
                    .addComponent(jTF_Juros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Cancelar)
                    .addComponent(jB_Continuar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_AbatimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_AbatimentoActionPerformed
        if(jCB_Abatimento.isSelected()){
            jTF_Abatimento.setEditable(true);
        }else{
            jTF_Abatimento.setEditable(false);
            jTF_Abatimento.setText("");
        }
    }//GEN-LAST:event_jCB_AbatimentoActionPerformed

    private void jCB_JurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_JurosActionPerformed
        if(jCB_Juros.isSelected()){
            jTF_Juros.setEditable(true);
        }else{
            jTF_Juros.setEditable(false);
            jTF_Juros.setText("");
        }
    }//GEN-LAST:event_jCB_JurosActionPerformed

    private void jTF_ValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_ValorKeyTyped
        String val = jTF_Valor.getText();
        char c = evt.getKeyChar();
        int ponto = val.indexOf(",")+3;
        int cursor = jTF_Valor.getCaretPosition();
        if(c==',' && val.contains(",")){
            evt.consume();
        }
        if(val.contains(",") && val.length()==ponto && cursor>ponto-3){
            evt.consume();
        }
        if(c==',' && cursor<val.length()-2){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_ValorKeyTyped

    private void jTF_AbatimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_AbatimentoKeyTyped
        String val = jTF_Abatimento.getText();
        char c = evt.getKeyChar();
        int ponto = val.indexOf(",")+3;
        int cursor = jTF_Abatimento.getCaretPosition();
        if(c==',' && val.contains(",")){
            evt.consume();
        }
        if(val.contains(",") && val.length()==ponto && cursor>ponto-3){
            evt.consume();
        }
        if(c==',' && cursor<val.length()-2){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_AbatimentoKeyTyped

    private void jTF_JurosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_JurosKeyTyped
        String val = jTF_Juros.getText();
        char c = evt.getKeyChar();
        int ponto = val.indexOf(",")+3;
        int cursor = jTF_Juros.getCaretPosition();
        if(c==',' && val.contains(",")){
            evt.consume();
        }
        if(val.contains(",") && val.length()==ponto && cursor>ponto-3){
            evt.consume();
        }
        if(c==',' && cursor<val.length()-2){
            evt.consume();
        }
    }//GEN-LAST:event_jTF_JurosKeyTyped

    private void jB_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CancelarMouseClicked
        Object[] options = { "Confirmar", "Cancelar" };
        int option = JOptionPane.showOptionDialog(null, "Cancelar operação?", null, JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);
        if(option == 0){super.dispose();}
    }//GEN-LAST:event_jB_CancelarMouseClicked

    private void jB_ContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ContinuarMouseClicked
        if(jTF_Descricao.getText().isEmpty() || jTF_Valor.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Deve colocar descrição e valor do gasto");
                }else{
                    if(jCB_Abatimento.isSelected() && jTF_Abatimento.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null,"Deve colocar o valor do abatimento");
                    }else{
                        if(jCB_Juros.isSelected() && jTF_Juros.getText().isEmpty()){
                            JOptionPane.showMessageDialog(null,"Deve colocar o valor do juros");
                        }else{
                            try{
                                Gasto gasto = new Gasto();
                                Consultas conn = new Consultas();
                                if(isUpdate()){
                                    gasto.setId(getGasto().getId());
                                }else{
                                    gasto.setId(conn.getNewID("gastos"));
                                }
                                
                                gasto.setDescricao(jTF_Descricao.getText());
                                System.out.println(gasto.getDescricao());
                                
                                int diaInt = Integer.parseInt(jCB_Dia.getSelectedItem().toString());
                                String mesString = (jCB_Mes.getSelectedItem()+"/"+jCB_Ano.getSelectedItem());
                                gasto.setDiaID(conn.getDiaID(diaInt, mesString));
                                gasto.setDia(diaInt);
                                gasto.setMes(mesString);
                                System.out.println(gasto.getDia()+"/"+gasto.getMes());
                                
                                gasto.setValor(Double.parseDouble(jTF_Valor.getText().replace(',', '.')));
                                System.out.println(gasto.getValor());
                                if(jCB_Abatimento.isSelected()){
                                    gasto.setAbatimento(true);
                                    gasto.setAbatimento_val(Double.parseDouble(jTF_Abatimento.getText().replace(',', '.')));
                                }else{
                                    gasto.setAbatimento(false);
                                    gasto.setAbatimento_val(0);
                                }
                                System.out.println(gasto.isAbatimento());
                                System.out.println(gasto.getAbatimento_val());
                                if(jCB_Juros.isSelected()){
                                    gasto.setJuros(true);
                                    gasto.setJuros_val(Double.parseDouble(jTF_Juros.getText().replace(',', '.')));
                                }else{
                                    gasto.setJuros(false);
                                    gasto.setJuros_val(0);
                                }
                                System.out.println(gasto.isJuros());
                                System.out.println(gasto.getJuros_val());
                                gasto.setValor_total(gasto.getValor()-gasto.getAbatimento_val()+gasto.getJuros_val());
                                System.out.println(gasto.getValor_total());
                                   
                                if(isUpdate()){
                                    boolean sucesso = conn.updateGasto(gasto);
                                    if(sucesso){
                                        JOptionPane.showMessageDialog(null, "Gasto atualizado com sucesso");
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Erro ao atualizar gasto");
                                    }
                                    dispose();
                                }else{
                                    boolean sucesso = conn.inserirGasto(gasto);
                                    if(sucesso){
                                        JOptionPane.showMessageDialog(null, "Gasto inserido com sucesso");
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Erro ao inserir gasto");
                                    }
                                }     
                            }catch(SQLException ex){
                                System.out.println("Erro ao inserir gasto");
                                System.out.println(ex);
                            }
                        }
                    }
                }
    }//GEN-LAST:event_jB_ContinuarMouseClicked

    private void jTF_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Inserir_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Inserir_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Inserir_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Inserir_Gasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Inserir_Gasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cancelar;
    private javax.swing.JButton jB_Continuar;
    private javax.swing.JCheckBox jCB_Abatimento;
    private javax.swing.JComboBox<String> jCB_Ano;
    private javax.swing.JComboBox<String> jCB_Dia;
    private javax.swing.JCheckBox jCB_Juros;
    private javax.swing.JComboBox<String> jCB_Mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTF_Abatimento;
    private javax.swing.JTextField jTF_Descricao;
    private javax.swing.JTextField jTF_Juros;
    private javax.swing.JTextField jTF_Valor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the update
     */
    public boolean isUpdate() {
        return update;
    }

    /**
     * @param update the update to set
     */
    public void setUpdate(boolean update) {
        this.update = update;
    }

    /**
     * @return the gasto
     */
    public Gasto getGasto() {
        return gasto;
    }

    /**
     * @param gasto the gasto to set
     */
    public void setGasto(Gasto gasto) {
        this.gasto = gasto;
    }
}
