/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle_de_gasto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB_AdicionarGasto = new javax.swing.JButton();
        jB_RevisarGastos = new javax.swing.JButton();
        jB_Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Controle de Gastos");

        jB_AdicionarGasto.setText("Adicionar Gasto");
        jB_AdicionarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_AdicionarGastoMouseClicked(evt);
            }
        });

        jB_RevisarGastos.setText("Revisar Gastos");
        jB_RevisarGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_RevisarGastosMouseClicked(evt);
            }
        });

        jB_Sair.setText("Sair do Programa");
        jB_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_SairMouseClicked(evt);
            }
        });

        jLabel2.setText("Criado por Gustavo CE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_AdicionarGasto)
                                .addGap(18, 18, 18)
                                .addComponent(jB_RevisarGastos)))
                        .addGap(18, 18, 18)
                        .addComponent(jB_Sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_RevisarGastos)
                    .addComponent(jB_AdicionarGasto)
                    .addComponent(jB_Sair))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_SairMouseClicked
        super.dispose();
        System.exit(0);
    }//GEN-LAST:event_jB_SairMouseClicked

    private void jB_AdicionarGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_AdicionarGastoMouseClicked
        Formulario_Inserir_Gasto form = new Formulario_Inserir_Gasto();
        form.setVisible(true);
    }//GEN-LAST:event_jB_AdicionarGastoMouseClicked

    private void jB_RevisarGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_RevisarGastosMouseClicked
        try {
            Object[] options = {"Exibir todos os gastos","Exibir total diarios","Exibir total mensais"};
            int escolha;
            escolha = JOptionPane.showOptionDialog(null, "Escolha oque exibir", null,JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options,null);
            switch(escolha){
                case 0:
                    Formulario_Revisar_Gastos form0 = new Formulario_Revisar_Gastos();
                    form0.setVisible(true);
                    break;
                case 1:
                    Formulario_Revisar_Gastos_Diarios form1 = new Formulario_Revisar_Gastos_Diarios();
                    form1.setVisible(true);
                    break;
                case 2:
                    Formulario_Revisar_Gastos_Mensais form2 = new Formulario_Revisar_Gastos_Mensais();
                    form2.setVisible(true);                    
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_RevisarGastosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_AdicionarGasto;
    private javax.swing.JButton jB_RevisarGastos;
    private javax.swing.JButton jB_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
